# Site settings
title: Kay Kimmett Tutoring
email: kay@kaykimmett.com
phone: 02380 000301
description: > # this means to ignore newlines until "baseurl:"
  Areas covered: Southampton, Portsmouth, Eastleigh, Fareham, Bitterne, Portswood, Whiteley, Hedge End, Chandler's Ford, Swanmore, Bursledon
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.kaykimmett.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
plugins_dir:
  - jekyll-redirect-from
